apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: conformitron-config-eks
spec:
  deletionPolicy: Orphan
  providerConfigRef:
    name: kubernetes-provider-eks
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: aws-auth
        namespace: kube-system
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: conformitron-namespace-eks
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: conformitron-namespace
  providerConfigRef:
    name: kubernetes-provider-eks