apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: conformitron-eksa
  namespace: upbound-system
spec:
  interval: 30s
  path: ./eks-anywhere-common/Addons/Partner/Lacework/Polygraph
  prune: true
  sourceRef:
    kind: GitRepository
    name: conformitron-eksa
  kubeConfig:
    secretRef:
      namespace: upbound-system
      name: eks-arm-us-east-2-1-28-eks-connection
      key: kubeconfig
